name: Release Workflow

on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+" # Run workflow on version tags, e.g. 1.0.0
        branches:
            - master # Add this to run on pushes to master branch
    workflow_dispatch: # Add this to enable manual triggering

permissions:
    contents: write # This is required for creating releases

jobs:
    build:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Need full history for tags and changelog generation

            - name: Get the version
              id: get_version
              run: |
                  if [[ $GITHUB_REF == refs/tags/* ]]; then
                    echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
                  else
                    # For workflow_dispatch, use the version from package.json
                    VERSION=$(node -p "require('./package.json').version")
                    echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
                  fi

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build plugin
              run: npm run build

            - name: Generate changelog
              run: npm run changelog

            - name: Extract changelog section
              id: extract_changelog
              run: |
                  VERSION=${{ steps.get_version.outputs.VERSION }}
                  # Create a temporary file for the extracted section
                  TEMP_FILE="release_notes.md"

                  # Read the changelog and extract the section for this version (handle both # and ## formats)
                  awk -v version="$VERSION" '
                    BEGIN { found=0; buffer="" }
                    /^[#]{1,2} \[?'$VERSION'\]?/ { found=1; buffer=$0; next }
                    found==1 && /^[#]{1,2} / { exit }
                    found==1 { buffer=buffer"\n"$0 }
                    END { print buffer }
                  ' CHANGELOG.md > $TEMP_FILE

                  # If the file is empty, use a default message
                  if [ ! -s $TEMP_FILE ]; then
                    echo "# Release $VERSION" > $TEMP_FILE
                    echo "" >> $TEMP_FILE
                    echo "## What's Changed" >> $TEMP_FILE
                    echo "- Version bump to $VERSION" >> $TEMP_FILE
                  fi

                  # Display the content of the release notes for debugging
                  echo "Generated release notes:"
                  cat $TEMP_FILE

            - name: Create release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ steps.get_version.outputs.VERSION }}
                  name: ${{ steps.get_version.outputs.VERSION }}
                  body_path: release_notes.md
                  files: |
                      main.js
                      manifest.json
                      styles.css
                  draft: false
                  prerelease: false
